### ISSUE TITLE
张鑫旭的 CSS 课程总结

### ISSUE THREAD

**Issue by ringcrl** [ringcrl/ringcrl.github.io#23]
慕课网上张鑫旭的 CSS 课程，讲的真心好~

**Comment by ringcrl** [comment]
### z-index
七阶层叠水平图
![2016-12-04 21 21 15](https://cloud.githubusercontent.com/assets/16740021/20866398/c40fb5da-ba67-11e6-99fd-ffb86d87a80f.png)

**Comment by ringcrl** [comment]
### line-height
消除图片底部间隙的方法，之前我都是一直 font-size:0;= =
1、图片块状化-无基线对其（inline和inline-block才会默默在图片后面加个p）
```
img{ display:block; }
```
2、图片底线对其
```
img{ vertical-align:bottom; }
```
3、行高足够小-基线位置上移
```
img{ line-height:0; }
```

**Comment by ringcrl** [comment]
### float
**清除浮动的方法**
```html
<div class="clearfix">
  <img src="xxx">
</div>
```
```css
.clearfix::after {
  content: '';
  display: table;
  clear: both;
}
```
